### PR TITLE
Change dependency from libgdal to gdal

### LINKED ISSUE #48: change dependency from libgdal to libgdal-core or gdal
### Comment:

The GDAL conda package has recently been revamped to seperate the core functionalities and a list of optional dependencies. It would be great if **pyogrio** users could have the advantages of this as well.

In practice a new `libgdal-core` package has been introduced, as well as a list of seperate packages with optional plugins. The old `libgdal` depends on all the new packages to have backwards compatibility.

The following optional GDAL dependencies were moved to seperate conda packages (reference https://github.com/conda-forge/gdal-feedstock/issues/722#issuecomment-2204537063):

- libgdal-arrow-parquet (arrow dependency)
- libgdal-jp2openjpeg (openjpeg dependency)
- libgdal-pdf (poppler dependency)
- libgdal-postgisraster (postgresql dependency)
- libgdal-pg (postgresql dependency)
- libgdal-fits (cfitsio dependency)
- libgdal-xls (freexls dependency)
- libgdal-grib (libaec dependency)
- libgdal-kea (kealib dependency)
- libgdal-tiledb (tiledb dependency)
- libgdal-netcd (libnetcdf dependency)
- libgdal-hdf4 (hdf4 dependency)
- libgdal-hdf5 (hdf5 dependency)

If a user wants to read a file where one of these dependencies is needed but unavailable, they will get a clean error, and just have to install the appropriate extra package to get it working.

An important thing to note is that the new `libgdal-core` package is only available for GDAL 3.9.1 at this time. Unless I'm mistaken, this would lead to new versions of **pyogrio** to only be installable with GDAL 3.9.1?

An alternative to avoid this could be to depend on the `gdal` package. This is the package that includes the GDAL python bindings, but the advantage is that for older versions this depends on `libgdal` and starting from 3.9.1 it depends on `libgdal-core`. This way it stays possible to install with an old GDAL.

### PR DESCRIPTION
**Pull request by theroggy**
GDAL recently reorganised its conda packages as discussed in https://github.com/conda-forge/gdal-feedstock/issues/722. In short: the `libgdal` package was split up in a core package, `libgdal-core`, and a list of seperate packages for many GDAL plugins, to be able to avoid the (large) footprint of the entire `libgdal`. For `pyogrio` this is also very relevant, as it depends on `libgdal` and most `pyogrio` users only need `libgdal-core`. 

However, as `libgdal-core` only exists for GDAL 3.9.1, just depending on `libgdal-core` would mean - as far as I know - that users of future versions of `pyogrio` could only install that new version in combination with GDAL 3.9.1, not with older versions of GDAL, as for those only the full `libgdal` package exists.

Because of this, this PR at the moment "proposes" to changed the dependency to the `gdal` package. This is the GDAL package with python bindings (which aren't needed for `pyogrio`), but the advantage is that for old versions of GDAL this depends on `libgdal`, but starting from GDAL 3.9.1 it depends on `libgdal-core`, so it can offer a workaround for the issue above.

If conda would offer an option to depend on `libgdal-core`, but if not available (for the needed version of GDAL), fallback to `libgdal`, that would be even better.

Closes #48.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by theroggy** [comment]
@conda-forge-admin please rerender

**Comment by theroggy** [comment]
@ocefpaf as described in the PR description above, we wonder if conda offers an option to depend on `libgdal-core`, but if (another dependency in) the conda environment needs an older version of GDAL, it would fallback to `libgdal`. Could you shed some light, or is depending on the `gdal` package the way to go?

**Comment by ocefpaf** [comment]
> @ocefpaf as described in the PR description above, we wonder if conda offers an option to depend on `libgdal-core`, but if (another dependency in) the conda environment needs an older version of GDAL, it would fallback to `libgdal`. Could you shed some light, or is depending on the `gdal` package the way to go?

If something requests older GDAL, an older build of pyogrio would also be selected. If you want to keep that as an option for future versions, then a variant would need to be built. IMO it is not worth the effort. Even more so given that the current pyogrio will be available for both for a while if we merge this one.

With that said. you are depending on `gdal` only here, that means conda will solve for whatever libgdal(-core or not) the `gdal` version requested is available.

Does that make sense?

**Comment by theroggy** [comment]
> If something requests older GDAL, an older build of pyogrio would also be selected. If you want to keep that as an option for future versions, then a variant would need to be built. IMO it is not worth the effort. Even more so given that the current pyogrio will be available for both for a while if we merge this one.
> 
> With that said. you are depending on `gdal` only here, that means conda will solve for whatever libgdal(-core or not) the `gdal` version requested is available.
> 
> Does that make sense?

Yes. This is indeed the reason I created this PR to depend on `gdal`. I expected this to be the only/best (practical) solution to be able to have recent versions of `pyogrio` use `libgdal-core` for new GDAL versions and `libgdal` for older GDAL versions.

Based on your answer, I think you agree?

**Comment by jorisvandenbossche** [comment]
But (and that's something I forgot when we chatted about this in our meeting), pyogrio binaries are built against a specific version of GDAL anyway. So it's not actually possible to install the latest pyogrio (assume the resulting binary of this rerendering) with an older version of GDAL. 
In that case the concern is a bit moot and it is actually fine to just directly depend on `libgdal-core`?

**Comment by theroggy** [comment]
Yes, indeed... in the corresponding rasterio issue I created (https://github.com/conda-forge/rasterio-feedstock/issues/303) this also was just mentioned...

I already encountered the case that with global pinning a rebuild was needed to use the latest version, but apparently the pinning is really on a specific version...
Kind of a weird situation, as in pyogrio we try to support keep support older gdal versions as well and the GDAL C API is binary compatible as far as I know...

**Comment by theroggy** [comment]
Another point raised in the rasterio topic: maybe better to wait for the next version (0.10 for pyogrio) as it can be seen as it can break an installation, even if it is easy to solve it?

**Comment by olivier-lacroix** [comment]
Hello there, I am looking forward to this change being merged to slim down our environments. I see very few, if any, open issues are linked to the 0.10 milestone: is there any target release date for 0.10 and the change in feedstock?

**Comment by jorisvandenbossche** [comment]
@olivier-lacroix indeed, we hope to release shortly. I opened an issue to track the release at https://github.com/geopandas/pyogrio/issues/470

**Comment by olivier-lacroix** [comment]
Thanks @jorisvandenbossche ! Looking forward to it!

**Pull request closed without merging**
